# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml
twitter: serrsch
github: selop

# Content
excerpt_link: Read More
fancybox: true

# Miscellaneous
google_analytics:
favicon: /images/favicon.ico
